version: "2"
# A Docker Compose file for configuration of the development environment

services:
  # load balancer
  lb:
    image: frjaraur/simplest-demo:simplestlb
    container_name: simplestlb # Do not allow scaling this service
    environment:
      - APPLICATION_ALIAS=simplestapp
      - APPLICATION_PORT=3000
    restart: unless-stopped
    networks:
      simplestdemo:
          aliases:
          - simplestlb
    ports:
      - 8181:80

  db:
    image: frjaraur/simplest-demo:simplestdb
    container_name: simplestdb # Don not allow scaling on this service yet ;)
    restart: unless-stopped
    environment:
        - "POSTGRES_PASSWORD=changeme"
    networks:
       simplestdemo:
        aliases:
          - simplestdb
    expose:
      - 5432

  app:
    image: frjaraur/simplest-demo:simplestapp
    environment:
      - dbhost=simplestdb
      - dbname=demo
      - dbuser=demo
      - dbpasswd=d3m0
    restart: unless-stopped
    networks:
       simplestdemo:
        aliases:
          - simplestapp
    expose:
      - 3000
    depends_on:
      - lb
      - db

networks:
  simplestdemo:
